### PR TITLE
shorten & reorder value props

### PR DESCRIPTION
**Pull request by uniqueg**
image

What do you think, @inutano, @neznayer, @swallow-ds?
But possibly we'd need new icons for column 2 (and maybe 3)...

### CODE REVIEW

**Comment by inutano** [comment]
LGTM

@swallow-ds would you find new icon candidates for 2 and 3?

**Comment by inutano** [comment]
any idea for the FAIRness icon? @uniqueg

**Comment by swallow-ds** [comment]
@inutano I just made the icon. I'd like to talk to you later.

**Comment by uniqueg** [comment]
image

With the new icons :)

**Pull request merged**
